# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entryform_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_entryForm(object):
    def setupUi(self, entryForm):
        entryForm.setObjectName("entryForm")
        entryForm.resize(400, 200)
        self.centralwidget = QtWidgets.QWidget(entryForm)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 406, 191))
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 0, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.modesBox = QtWidgets.QComboBox(self.centralwidget)
        self.modesBox.setGeometry(QtCore.QRect(10, 20, 111, 22))
        self.modesBox.setObjectName("modesBox")
        self.modesBox.addItem("")
        self.modesBox.addItem("")
        self.openDialogButton = QtWidgets.QPushButton(self.centralwidget)
        self.openDialogButton.setGeometry(QtCore.QRect(290, 20, 91, 21))
        self.openDialogButton.setObjectName("openDialogButton")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(240, 160, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.encodingLine = QtWidgets.QLineEdit(self.centralwidget)
        self.encodingLine.setEnabled(False)
        self.encodingLine.setGeometry(QtCore.QRect(10, 70, 113, 20))
        self.encodingLine.setObjectName("encodingLine")
        self.delLine = QtWidgets.QLineEdit(self.centralwidget)
        self.delLine.setEnabled(False)
        self.delLine.setGeometry(QtCore.QRect(10, 120, 111, 20))
        self.delLine.setObjectName("delLine")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.statusbar = QtWidgets.QStatusBar(entryForm)
        self.statusbar.setGeometry(QtCore.QRect(0, 0, 3, 18))
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(entryForm)
        QtCore.QMetaObject.connectSlotsByName(entryForm)

    def retranslateUi(self, entryForm):
        _translate = QtCore.QCoreApplication.translate
        entryForm.setWindowTitle(_translate("entryForm", "Entry form"))
        self.label.setText(_translate("entryForm", "Режим:"))
        self.label_2.setText(_translate("entryForm", "Файл / БД"))
        self.modesBox.setItemText(0, _translate("entryForm", "Редактирование"))
        self.modesBox.setItemText(1, _translate("entryForm", "Создание csv"))
        self.openDialogButton.setText(_translate("entryForm", "Выбрать"))
        self.label_3.setText(_translate("entryForm", "Кодировка:"))
        self.label_4.setText(_translate("entryForm", "Разделитель:"))
